project:
  name: rag-question-answering
  version: 0.1.0
  description: A Retrieval-Augmented Generation (RAG) question-answering system using LangChain, ChromaDB, and HuggingFace/OpenAI embeddings.


debug: True

# the folder name of the knowledge documents
knowledge-base: knowledge-base

chunking:
  # embedding (SemanticChunker) > llm > recursive (RecursiveCharacterTextSplitter)
  chunking_method: embedding  # "recursive", "llm", or "embedding"
  chunking_emb: text-embedding-3-small 
  chunking_llm: gpt-4.1-nano
  chunk_size: 500
  chunk_overlap: 150
  workers: 4


vectorDB:
  name: vector-db
  collection_name: docs
  # openai embedding model is better
  embedding_method: &cp openai  # "huggingface" or "openai"
  hf_model: all-MiniLM-L6-v2
  openai_model: text-embedding-3-small


answer_generation:
  model: gpt-4.1-mini
  temperature: 0.0
  max_tokens: 2048
  top_p: 1.0


evaluation:
  database_embedding: *cp  # no need
  model: gemini-2.5-flash

