import os
from pathlib import Path
from typing import List, Optional

from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_chroma import Chroma
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.messages import SystemMessage, HumanMessage, convert_to_messages
from langchain_core.chat_history import InMemoryChatMessageHistory
from langchain_core.runnables.history import RunnableWithMessageHistory

from dotenv import load_dotenv

from src.utils.prompts import system_prompt
from src.utils.pydantic_models import Answer
from src.utils.utils import CONFIG

load_dotenv(override=True)


PROJECT_ROOT = Path(__file__).parent.parent.parent
KNOWLEDGE_BASE_DIR = str(PROJECT_ROOT / CONFIG["knowledge-base"])    
VECTOR_DB_NAME = str(PROJECT_ROOT / CONFIG["vectorDB"]["name"])        
COLLECTION_NAME = CONFIG["vectorDB"]["collection_name"]

VECTOR_DB = Chroma(
        collection_name=COLLECTION_NAME, persist_directory=VECTOR_DB_NAME
    )


EMBEDDING_METHOD = CONFIG["vectorDB"]["embedding_method"]  # or "openai"
if EMBEDDING_METHOD == "huggingface":
    EMBEDDING = HuggingFaceEmbeddings(model_name=CONFIG["vectorDB"]["hf_model"])
elif EMBEDDING_METHOD == "openai":
    print("use openai embedding model")
    EMBEDDING = OpenAIEmbeddings(
        model=CONFIG["vectorDB"]["openai_model"]
    )

LLM = ChatOpenAI(
    model=CONFIG["answer_generation"]["model"], 
    temperature=CONFIG["answer_generation"]["temperature"], 
    max_tokens=CONFIG["answer_generation"]["max_tokens"], 
    top_p=CONFIG["answer_generation"]["top_p"]
).with_structured_output(Answer)



def retrieve_chunks(
    question: str,
    top_k: int = 5,
    vector_db: Chroma = VECTOR_DB,
    embedding: OpenAIEmbeddings | HuggingFaceEmbeddings = EMBEDDING,
) -> list:
    """Retrieve relevant chunks from the vector database based on the user's question.
    Args:
        question: The user's question to be answered.
        vector_db: The Chroma vector database containing the document chunks.
        top_k: The number of top relevant chunks to retrieve.
        embedding: The embedding model to use for embedding the question.
    returns: List of retrieved chunks relevant to the question.
    """
    question_embedding = embedding.embed_query(question)
    # query the vector database for relevant chunks
    results = vector_db.similarity_search_by_vector(question_embedding, k=top_k)

    return results


def combine_question(question: str, history: list = []) -> str:
    """
    Combine all the user's messages into a single string.
    Args:
        question: the latest user question
        history: the conversation in the past, including user message and model response
    """
    old = ""
    if history:
        old_content = [m["content"] for m in history if m["role"] == "user"]
        if old_content and type(old_content[0]) is list:
            old_content = [c[0]["text"] for c in old_content]
        old = "\n".join(old_content)
    return old + "\n" + question


def llm_answer(
    question: str,
    history: List = [],
    retrieved_chunks: list = [],
    llm_model: ChatOpenAI = LLM,
) -> str:
    """Answer the user's question using retrieved chunks from the vector database and an LLM.
    Args:
        question: The user's question to be answered.
        history:
        retrieved_chunks: The list of retrieved chunks from the vector database.
        llm_model: The LLM model to use for generating the answer
    returns: The answer generated by the LLM based on the retrieved chunks and the user's question.
    """
    ##### messages list should contain:
    # (1) system message,
    # (2) (Optional) historical message including the human/user message and model response
    # (3) latest human/user message

    # (1) system message with context imputed
    # chunks are retrieved from vector db,
    # the content of the chunk is in the page_content attribute,
    # and the metadata is in the metadata attribute
    context = "\n\n".join([chunk.page_content for chunk in retrieved_chunks])
    system = system_prompt(context)
    messages = [SystemMessage(content=system)]

    # (2) historical messages
    # messages.extend(convert_to_messages(history))
    if history:
        messages.extend(convert_to_messages(history))

    # (3) latest human message
    messages.append(HumanMessage(question))

    response = llm_model.invoke(messages)

    # here the answer is NOT in response.answer
    # HERE As the model is configured to return a structured output,
    # we expect the response to be in the format of the Answer pydantic model,
    # which has the fields "answer" and "source"
    return response


def answer_question(
    question: str, 
    history: List = [], 
    top_k: int = 5, 
    embedding: HuggingFaceEmbeddings | OpenAIEmbeddings = EMBEDDING,
    llm_model: ChatOpenAI = LLM
) -> None:

    # only care about the recent conversations
    if history:
        length = len(history)
        history = history[max(-length // 2, -5) :]

    # combine latest question with history
    c_question = combine_question(question=question, history=history)

    # Retrieve relevant chunks from the vector database based on all the historical conversation and latest question
    retrieved_chunks = retrieve_chunks(
        c_question, vector_db=VECTOR_DB, top_k=top_k, embedding=embedding
    )

    if CONFIG["debug"]:
        print(f"Retrieved {len(retrieved_chunks)} chunks from the vector database:")
        for i, chunk in enumerate(retrieved_chunks):
            print(chunk)
            print(f"Chunk {i+1}: {chunk.metadata.get('headline', 'No headline')}")
            print(f"Chunk {i+1} text: {chunk.page_content[:100]}...")
            print("-" * 50)

    # answer the question using the retrieved chunks and LLM
    result = llm_answer(
        question,
        history=history,
        retrieved_chunks=retrieved_chunks,
        llm_model=llm_model,
    )

    print(f"Question: {question}\n")
    print(f"Answer: {result.answer}\n")
    print(f"Source: {result.source}\n")

    return result.answer, retrieved_chunks


if __name__ == "__main__":
    question = "What are the company's products?"
    history = [("user", ""), ("ai", "")]
    answer_question(question=question, history=[], top_k=5, llm_model=LLM)
