import os
from pathlib import Path
from typing import List, Optional

from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_chroma import Chroma
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.messages import SystemMessage, HumanMessage
from langchain_core.documents import Document

from dotenv import load_dotenv

from src.utils.prompts import system_prompt
from src.utils.pydantic_models import Answer


load_dotenv(override=True)

DEBUG = True

KNOWLEDGE_BASE_DIR = str(Path(__file__).parent.parent.parent / "knowledge-base")
VECTOR_DB_NAME = str(Path(__file__).parent.parent.parent / "vector-db")
COLLECTION_NAME = "docs"

EMBEDDING_METHOD = "huggingface"  # or "openai"
if EMBEDDING_METHOD == "huggingface":
    EMBEDDING = HuggingFaceEmbeddings(
                    model_name="all-MiniLM-L6-v2")
elif EMBEDDING_METHOD == "openai":
    EMBEDDING = OpenAIEmbeddings(
        model="text-embedding-3-small", 
        model_kwargs={
            "temperature": 0.0, 
            "max_tokens": 2048, 
            "top_p": 1.0,
            }
    )

QUESTION_ANSERING_LLM = "gpt-4.1-mini"
LLM = ChatOpenAI(
    model=QUESTION_ANSERING_LLM, 
    temperature=0.0, 
    max_tokens=2048, 
    top_p=1.0
    ).with_structured_output(Answer)



def retrieve_chunks(
        question: str, 
        vector_db: Chroma, 
        top_k: int = 5, 
        embedding: OpenAIEmbeddings | HuggingFaceEmbeddings = EMBEDDING
        ) -> list:
    """Retrieve relevant chunks from the vector database based on the user's question.
    Args:
        question: The user's question to be answered.
        vector_db: The Chroma vector database containing the document chunks.
        top_k: The number of top relevant chunks to retrieve.
        embedding: The embedding model to use for embedding the question.
    returns: List of retrieved chunks relevant to the question.
    """  
    question_embedding = embedding.embed_query(question)

    # query the vector database for relevant chunks
    results = vector_db.similarity_search_by_vector(question_embedding, k=top_k)
    
    return results


def llm_answer(
        question: str, 
        retrieved_chunks: list,
        llm_model: ChatOpenAI = LLM
        ) -> str:
    """Answer the user's question using retrieved chunks from the vector database and an LLM.
    Args:
        question: The user's question to be answered.
        retrieved_chunks: The list of retrieved chunks from the vector database.
        llm_model: The LLM model to use for generating the answer
    returns: The answer generated by the LLM based on the retrieved chunks and the user's question.
    """
    # chunks are retrieved from vector db, 
    # the content of the chunk is in the page_content attribute, 
    # and the metadata is in the metadata attribute
    context = "\n\n".join([chunk.page_content for chunk in retrieved_chunks])
    system = system_prompt(context)

    # Step 3: Pass the prompt to the LLM to generate an answer
    messages = [SystemMessage(content=system), 
         HumanMessage(content=question)]
         
    response = llm_model.invoke(messages)

    # here the answer is NOT in response.answer
    # HERE As the model is configured to return a structured output, 
    # we expect the response to be in the format of the Answer pydantic model, 
    # which has the fields "answer" and "source"
    return response


def answer_question(
        question: str,
        top_k: int = 5,
        ) -> None:
    
    # 1. load the vector database
    vector_db = Chroma(
        collection_name=COLLECTION_NAME, 
        persist_directory=VECTOR_DB_NAME,
        embedding_function=EMBEDDING
    )

    # 2. Retrieve relevant chunks from the vector database
    retrieved_chunks = retrieve_chunks(
        question, 
        vector_db, 
        top_k=top_k,
        embedding=EMBEDDING)
    
    if DEBUG:
        print(f"Retrieved {len(retrieved_chunks)} chunks from the vector database:")
        for i, chunk in enumerate(retrieved_chunks):
            print(chunk)
            print(f"Chunk {i+1}: {chunk.metadata.get('headline', 'No headline')}")
            print(f"Chunk {i+1} text: {chunk.page_content[:100]}...")
            print("-" * 50)

    # answer the question using the retrieved chunks and LLM
    result = llm_answer(
        question, 
        retrieved_chunks=retrieved_chunks,
        llm_model=LLM
    )

    print(f"Question: {question}\n")
    print(f"Answer: {result.answer}\n")
    print(f"Source: {result.source}\n")

if __name__ == "__main__":
    question = "What are the company's products?"
    answer_question(        
        question=question,
        top_k=5
    )
    
